# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/other/Constraints.xdc

# Block Designs: bd/mem/mem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem || ORIG_REF_NAME==mem}]

# IP: bd/mem/ip/mem_blk_mem_gen_0_0/mem_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_blk_mem_gen_0_0 || ORIG_REF_NAME==mem_blk_mem_gen_0_0}]

# XDC: bd/mem/mem_ooc.xdc
