# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.cache/wt [current_project]
set_property parent.project_path /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/student/Dzmitry_Mikialevich/cpu_src/other/mem_init_start.coe
read_verilog -library xil_defaultlib {
  /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/imports/src/pulsegen.v
  /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/imports/src/uart_tx.v
  /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/imports/src/prescaler.v
  /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/imports/src/clocknx.v
  /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/imports/src/debouncer.v
  /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/imports/src/cpu.v
  /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/imports/src/dbgu.v
  /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/bd/mem/hdl/mem_wrapper.v
  /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/imports/src/toplevel.v
}
add_files /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/bd/mem/mem.bd
set_property used_in_implementation false [get_files -all /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/bd/mem/ip/mem_blk_mem_gen_0_0/mem_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/bd/mem/mem_ooc.xdc]
set_property is_locked true [get_files /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/bd/mem/mem.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/constrs_1/imports/other/Constraints.xdc
set_property used_in_implementation false [get_files /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/constrs_1/imports/other/Constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top toplevel -part xc7z010clg400-1


write_checkpoint -force -noxdef toplevel.dcp

catch { report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb }
