# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/bd/mem/ip/mem_blk_mem_gen_0_0/mem_blk_mem_gen_0_0.xci
# IP: The module: 'mem_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/bd/mem/ip/mem_blk_mem_gen_0_0/mem_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/bd/mem/ip/mem_blk_mem_gen_0_0/mem_blk_mem_gen_0_0.xci
# IP: The module: 'mem_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student/Dzmitry_Mikialevich/dzmitrymikialevich/dzmitrymikialevich.srcs/sources_1/bd/mem/ip/mem_blk_mem_gen_0_0/mem_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
